title: Shiju
logo: "images/logo.svg" # You can add own logo image.
description: Make or break things
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Shiju P K
  bio: Hi, my name is Shiju. Thank you for visiting my blog.

# Contact links
twitter: https://twitter.com/shijupk # Add your Twitter handle
github: https://github.com/shijupk # Add your Facebook handle
instagram: https://instagram.com/shijupk # Add your Instagram handle
linkedin: https://linkedin.com/in/shijupk # Add your Pinterest handle
email: shijupk@gmail.com # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Shiju's make or break blog # Add your hero title
hero-subtitle: my coding experiments # Add your hero subtitle
hero-image: images/13.jpg # Add background image in section hero

# Footer
footer-image: # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: shijupk-github-io # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "UA-163831052-1" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "github.us4.list-manage.com/subscribe/post?u=79747205163f508c3b7fb94f8&amp;id=cf0e1b3ed1" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed